# Base configs
baseurl: "https://sunprinces.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "On my way"
subtitle: "See the world through my eyes!"
author: "Tony Hsu"
header:
 title: "Photography"
 subtitle: "by Tony Hsu"
web_design: "AJ"
social_urls:
  twitter: "https://twitter.com/sunprinceS_0822"
  instagram: "https://www.instagram.com/sunprince822"
  wordpress: "https://sunprincelife.wordpress.com/"
  flickr: "https://www.flickr.com/photos/147409487@N06/albums"
  github: "https://github.com/sunprinceS/photography"
